### ISSUE TITLE
[Bug] Duplicate rows in `int_quickbooks__invoice_join.sql` model when more than one QuickBooks source

### ISSUE THREAD

**Issue by MatteyRitch** [fivetran/dbt_quickbooks#120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Pulling from the int_quickbooks__invoice_join model can return duplicate payments (different payment_ids based on the source) for the same invoice. 

The CTEs aliased as "invoice_est" and "invoice_pay" bring in the invoice_id and payment_id and join only on invoice_id.
If the same invoice_id exists in multiple quickbooks sources, there will be a cross join that causes duplicate entries in these CTE results which is then propagated when they are used downstream.

### Expected behavior

Only have payments that were associated with a given invoice returned.

### dbt Project configurations

```
vars: 
  quickbooks_union_schemas: ['quickbooks','quickbooks_source2', 'quickbooks_source3']

models:
  quickbooks:
      +schema: null
  quickbooks_source:
      +schema: null
```

### Package versions

```
  - package: fivetran/quickbooks
    version: [">=0.12.0", "<0.13.0"] 
```

### What database are you using dbt with?

postgres

### dbt Version

```
dbt v1.7.0-latest
```

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.
