### ISSUE TITLE
[Bug] Invoices with 0 balance due because of deposit being applied result in incorrect revenue on P&L

### ISSUE THREAD

**Issue by sbrudz** [fivetran/dbt_quickbooks#122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

**UPDATE from @fivetran-avinash**: After investigating with @sbrudz, we've determined that the `invoice_lines.amount` is the right value to bring in for most transaction amounts. 

The reason that `invoices.total_amount=0` was ever brought in was due to unique issues presented by zero invoice bundle amounts that had non-zero line items that summed up to a non-zero invoice when it should have been zero, leading to overcounting in the general ledger. These specific invoice line bundle cases will need to be addressed, but for the majority of issues the invoice_line.amount should suffice for transaction amounts to bring in all the needed transaction values. 

Initial issue presented by @sbrudz: 

We have clients that pay an upfront deposit and then when we complete work for them, we apply that deposit to their final invoice.  The workflow is described in this [Quickbooks article](https://quickbooks.intuit.com/learn-support/en-us/help-article/invoicing/manage-upfront-deposits-retainers/L7dNnFGBi_US_en_US).

We've found that if the total balance of the invoice is 0, then the revenue from that invoice isn't being counted in the quickbooks__profit_and_loss model.

### Expected behavior

Given: A customer has a $10k deposit in a liability account and then we apply that $10k deposit to their last invoice which has $10k in charges resulting in a $0 invoice total, the resulting `stg_quickbooks_invoice_line` table looks like:

| Invoice ID | Index | Amount | Detail Type | Sales Item Account ID |
| --- | --- | --- | --- | --- |
| 14510 | 0 | 10000 | SalesItemLineDetail | 218 |
| 14510 | 1 | -10000 | SalesItemLineDetail | 210 |
| 14510 | 2 | 0 | SubTotalLineDetail |  |

If that's the only invoice for the month, I should see $10k in revenue from account 218 on the Profit and Loss statement.

### dbt Project configurations

```yml
name: "bug_report"
version: "1.0.0"
require-dbt-version: ">=1.7.0"
config-version: 2

profile: "bug_report"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  salesforce:
    +schema: sales
  salesforce_source:
    +schema: stg_salesforce
  quickbooks:
    +schema: finance
    double_entry_transactions:
      +schema: int_quickbooks
  quickbooks_source:
    +schema: stg_quickbooks

vars:
  using_department: false
  using_estimate: false
  using_invoice_bundle: false
  using_refund_receipt: false
  using_sales_receipt: false
  using_purchase_order: false
```

### Package versions

```yml
packages:
  - package: fivetran/salesforce
    version: [">=1.0.0", "<1.1.0"]
  - package: fivetran/quickbooks
    version: [">=0.12.0", "<0.13.0"]
```

### What database are you using dbt with?

snowflake

### dbt Version

```
Core:
  - installed: 1.7.10
  - latest:    1.7.11 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - snowflake: 1.7.2 - Update available!
  - duckdb:    1.7.3 - Up to date!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation
```

### Additional Context

If the invoice has a non-zero total, then the revenue shows up as expected.  It seems like the problem is with these lines in [int_quickbooks__invoice_double_entry.sql](https://github.com/fivetran/dbt_quickbooks/blob/v0.12.3/models/double_entry_transactions/int_quickbooks__invoice_double_entry.sql#L103-L106).  I'd be happy to contribute a PR, but I don't understand enough about why the logic was added (in [this commit](https://github.com/fivetran/dbt_quickbooks/commit/cb81ebc39186c5db780e6e87079c08ca923b2dca#diff-9e6e18596c40be17701777112b4b9afc752ebf0edda164ab4c73903a8b5c157dR87-R89)).  It seems like changing it incorrectly could break other things.

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.
