### ISSUE TITLE
Tests error

### ISSUE THREAD

**Issue by ron-keler** [fivetran/dbt_quickbooks#72]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Hi team, thanks for meeting today! As discussed, when deploying the package, got 2 tests errors:
 - not_null_stg_quickbooks__bill_linked_txn_bill_payment_id 
 - dbt_utils_unique_combination_of_columns_quickbooks__general_ledger_unique_id__source_relation  
The GL unique_id error seems to be the result of us having account IDs that have the same name.
The bill txn error seems to be the result of having unpaid transactions that have no payment ID

Thanks! - Ron

### Relevant error log or model output

```shell
19:05:26  81 of 167 START test not_null_stg_quickbooks__bill_linked_txn_bill_payment_id .. [RUN]
19:05:26  81 of 167 FAIL 405 not_null_stg_quickbooks__bill_linked_txn_bill_payment_id .... [FAIL 405 in 0.14s]

19:05:31  157 of 167 START test dbt_utils_unique_combination_of_columns_quickbooks__general_ledger_unique_id__source_relation  [RUN]
19:05:32  157 of 167 FAIL 21773 dbt_utils_unique_combination_of_columns_quickbooks__general_ledger_unique_id__source_relation  [FAIL 21773 in 0.27s]
```

### Expected behavior

We discussed changing the GL unique ID to kep off account ID and not name, and consider removing the payment_id not null test

### dbt Project configurations

Vanilla config, no changes made..:

```yml
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'my_new_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  my_new_project:
    # Applies to all files under models/example/
    example:
      materialized: view
```
### Package versions

packages:
  - package: fivetran/quickbooks
    version: [">=0.7.0", "<0.8.0"]

### What database are you using dbt with?

postgres

### dbt Version

1.4

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.
