### ISSUE TITLE
[Feature] Databricks Compatibility

### ISSUE THREAD

**Issue by fivetran-catfritz** [fivetran/dbt_quickbooks#89]
*Copied from [fivetran/dbt_mixpanel #34](https://github.com/fivetran/dbt_mixpanel/issues/34).*

### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

For Databricks Compatibility, add the following:
1. Buildkite testing:
    - Update `pre-command` ([example](https://github.com/fivetran/dbt_mailchimp/pull/37/files#diff-71e4f7cc0d357183cbbb900bb97a29db006263fb1967d06035e417c38f27e53d))
    - Update `pipeline.yml` ([example](https://github.com/fivetran/dbt_mailchimp/pull/37/files#diff-a3991ebf1475eb82acab13946ffc1eca02b43917f6d5bec3898f45c8b0b9bd53))
    - Update `sample.profiles.yml` ([example](https://github.com/fivetran/dbt_mailchimp/pull/37/files#diff-6027a8a0697f904fa96d43fff38bc88db621fd2bb8ca38cb9902a67140e014b0))
    - Add the below to `integration_tests/dbt_project.yml` if it's not there:
```yml
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']
```
2. For `source` packages, update src yml so a database won't be passed to spark ([example](https://github.com/fivetran/dbt_mailchimp_source/pull/15/files#diff-e30faf0b3c3cf10a3abdff02f8935a91bd3c72995866d2fa3f3c0d528cd6a7da) or use below):
```yml
sources: 
  - name: <name>
    database: "{% if target.type != 'spark' %}{{ var('<name>_database', target.database) }}{% endif %}"
```
3. Update any incremental models to update partition_by for databricks and add current strategies if not present:
```yml
config(
        materialized='incremental',
        unique_key='<original unique key>',
        partition_by={'field': '<original field>', 'data_type': '<original data type>'} if target.type not in ('spark','databricks') else ['<original field>'],
        incremental_strategy = 'merge' if target.type not in ('postgres', 'redshift') else 'delete+insert',
        file_format = 'delta' 
)
```

### Are you interested in contributing this feature?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.
