### ISSUE TITLE
[Bug] Can't install package due to external connection exception

### ISSUE THREAD

**Issue by antoniofranciscoandrade** [fivetran/dbt_quickbooks#90]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Running `dbt deps` returns the following error:

```
03:33:17  Running with dbt=1.5.0
03:33:24  Encountered an error:
External connection exception occurred: Unterminated string starting at: line 1 column 10213 (char 10212)
```

My packages.yml file contains the following:

```
packages:
  - package: fivetran/quickbooks
    version: 0.9.0
```

### Relevant error log or model output

```shell
03:33:17  Running with dbt=1.5.0
03:33:24  Encountered an error:
External connection exception occurred: Unterminated string starting at: line 1 column 10213 (char 10212)
```

### Expected behavior

Package should be able to install

### dbt Project configurations

My dbt_project.yml is the following:

```
name: "transformations"
version: "1.0.0"
config-version: 2

vars:
  quickbooks_union_schemas: ["schema_a", "schema_b"]

profile: "transformations"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
 
models:
  transformations:
    example:
      +materialized: view
```

### Package versions
```
packages:
  - package: fivetran/quickbooks
    version: 0.9.0
```
### What database are you using dbt with?

postgres

### dbt Version

1.5.0

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [X] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.
